config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'clients#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :clients, only: %i[index show edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
# frozen_string_literal: true

class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: %i[show edit update]

  def index
    @clients = []

    service = ClientService.new(session[:auth_token])
    result = service.search(
      fields: "nom,adresse,ville,tel",
      nom: params[:nom],
      ville: params[:ville],
      limit: params[:limit] || 50
    )

    if result[:success]
      @clients = result[:data].is_a?(Array) ? result[:data] : [result[:data]].compact
    else
      flash.now[:alert] = result[:error]
    end
  end

  def show
    return unless @client.nil?

    redirect_to clients_path, alert: 'Client not found'
  end

  def edit
    return unless @client.nil?

    redirect_to clients_path, alert: 'Client not found'
  end

  def update
    service = ClientService.new(session[:auth_token])
    result = service.update(params[:id], client_params)

    if result[:success]
      flash[:notice] = 'Client updated successfully'
      redirect_to client_path(params[:id])
    else
      flash.now[:alert] = result[:error]
      render :edit
    end
  end

  private

  def set_client
    service = ClientService.new(session[:auth_token])
    result = service.find(params[:id])
    @client = result[:data] if result[:success]
  end

  def client_params
    params.require(:client).permit(:nom, :email, :tel, :ville, :adresse, :code_postal)
  end

  def authenticate_user!
    return if session[:auth_token].present?

    redirect_to login_path, alert: 'Please log in first'
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    result = AuthService.authenticate(params[:username], params[:password])

    if result[:success]
      session[:auth_token] = result[:token]

      redirect_to clients_path, notice: 'Logged in successfully'
    else
      flash.now[:alert] = result[:error]
      render :new
    end
  end

  def destroy
    session[:auth_token] = nil
    redirect_to login_path, notice: 'Logged out successfully'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clients/edit.html.slim
.card.card-header
    h2.title = "#{@client['nom']}"
    = link_to edit_client_path(@client['id']), class: "btn btn-primary flex items-center gap-1" do
      svg width="10" height="10" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"
        path fill="#ffffff" d="M195.1 9.5c3-14.8 16.1-25.5 31.3-25.5h59.8c15.2 0 28.3 10.7 31.3 25.5l14.5 70c14.1 6 27.3 13.7 39.3 22.8l67.8-22.5c14.4-4.8 30.2 1.2 37.8 14.4l29.9 51.8c7.6 13.2 4.9 29.8-6.5 39.9L447 233.3c.9 7.4 1.3 15 1.3 22.7s-.5 15.3-1.3 22.7l53.4 47.5c11.4 10.1 14 26.8 6.5 39.9L477 417.9c-7.6 13.1-23.4 19.2-37.8 14.4l-67.8-22.5c-12.1 9.1-25.3 16.7-39.3 22.8l-14.4 69.9c-3.1 14.9-16.2 25.5-31.3 25.5h-59.8c-15.2 0-28.3-10.7-31.3-25.5l-14.4-69.9c-14.1-6-27.2-13.7-39.3-22.8l-68.1 22.5c-14.4 4.8-30.2-1.2-37.8-14.4L5.8 366.1c-7.6-13.2-4.9-29.8 6.5-39.9l53.4-47.5c-.9-7.4-1.3-15-1.3-22.7s.5-15.3 1.3-22.7l-53.4-47.5C.9 175.7-1.7 159 5.8 145.9l29.9-51.8c7.6-13.2 23.4-19.2 37.8-14.4l67.8 22.5c12.1-9.1 25.3-16.7 39.3-22.8zM256.3 336a80 80 0 1 0-.6-160a80 80 0 1 0 .6 160"
      | Éditer

.card.card_form
  h3 EDITION

  = form_with url: client_path(@client['id']), method: :patch, scope: :client, local: true do |f|
    .info-grid
      .info-row
        .info-label Prénom & NOM
        .info-value
          = f.text_field :nom, value: @client['nom'], placeholder: "Nom"

      .info-row
        .info-label Téléphone
        .info-value = f.text_field :tel, value: @client['tel']

      .info-row
        .info-label Email
        .info-value = f.email_field :email, value: @client['email']

      .info-row
        .info-label Adresse
        .info-value = f.text_field :adresse, value: @client['adresse']

      .info-row
        .info-label Code postal
        .info-value = f.text_field :code_postal, value: @client['code_postal'], class: 'code_postal'

      .info-row
        .info-label Ville
        .info-value = f.text_field :ville, value: @client['ville']

    .actions-right
      = link_to "Annuler", client_path(@client['id']), class: "btn btn-light"
      = f.submit "Enregistrer", class: "btn btn-success"

app/views/clients/index.html.slim
.card
  .title
    | Recherche d'une fiche de contact

.card.search_form
  = form_with url: clients_path, method: :get, local: true do |f|
    .form-group
      = f.label :nom, "Renseigner un nom ou une dénomination"
      = f.text_field :nom, placeholder: "Nom ou dénomination", value: params[:nom]
    = f.submit "Rechercher", class: "btn btn-primary", name: "search"

table
  colgroup
    col style="width: 60px;"
    col style="width: 200px;"
    col style="width: 300px;"
    col style="width: 150px;"
    col style="width: 150px;"
    col style="width: 100px;"
  thead
    tr
      th
      th Nom
      th Adresse
      th Ville
      th Téléphone
      th
  tbody
    - if @clients.any?
      - @clients.each do |client|
        tr
          td
            .client-name
              .avatar
                = client['nom'].to_s.split[0, 2].map { |w| w[0].upcase }.join
          td = client['nom']
          td = client['adresse']
          td = client['ville']
          td = client['tel']
          td
            = link_to client_path(client['id']), class: "btn btn-secondary" do
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 20 20"><path fill="#ffffff" d="M12.9 14.32a8 8 0 1 1 1.41-1.41l5.35 5.33l-1.42 1.42l-5.33-5.34zM8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"/></svg>
              | Voir

    - else
      tr
        td [colspan="6"] Aucun contact trouvé.

app/views/clients/show.html.slim
.card.card-header
    h2.title = "#{@client['nom']}"
    = link_to edit_client_path(@client['id']), class: "btn btn-primary flex items-center gap-1" do
      <svg width="10" height="10" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="#ffffff" d="M195.1 9.5c3-14.8 16.1-25.5 31.3-25.5h59.8c15.2 0 28.3 10.7 31.3 25.5l14.5 70c14.1 6 27.3 13.7 39.3 22.8l67.8-22.5c14.4-4.8 30.2 1.2 37.8 14.4l29.9 51.8c7.6 13.2 4.9 29.8-6.5 39.9L447 233.3c.9 7.4 1.3 15 1.3 22.7s-.5 15.3-1.3 22.7l53.4 47.5c11.4 10.1 14 26.8 6.5 39.9L477 417.9c-7.6 13.1-23.4 19.2-37.8 14.4l-67.8-22.5c-12.1 9.1-25.3 16.7-39.3 22.8l-14.4 69.9c-3.1 14.9-16.2 25.5-31.3 25.5h-59.8c-15.2 0-28.3-10.7-31.3-25.5l-14.4-69.9c-14.1-6-27.2-13.7-39.3-22.8l-68.1 22.5c-14.4 4.8-30.2-1.2-37.8-14.4L5.8 366.1c-7.6-13.2-4.9-29.8 6.5-39.9l53.4-47.5c-.9-7.4-1.3-15-1.3-22.7s.5-15.3 1.3-22.7l-53.4-47.5C.9 175.7-1.7 159 5.8 145.9l29.9-51.8c7.6-13.2 23.4-19.2 37.8-14.4l67.8 22.5c12.1-9.1 25.3-16.7 39.3-22.8zM256.3 336a80 80 0 1 0-.6-160a80 80 0 1 0 .6 160"/></svg>
      | Éditer

.card.card_form
  h3 INFORMATIONS
  .info-grid
    .info-row
      .info-label Prénom & NOM
      .info-value = "#{@client['nom']}"

    .info-row
      .info-label Téléphone
      .info-value = @client['tel']

    .info-row
      .info-label Email
      .info-value = @client['email']

    .info-row
      .info-label Adresse
      .info-value
        = @client['adresse']
        br
        = "#{@client['code_postal']} #{@client['ville']}"

app/views/layouts/application.slim
doctype html
html
  head
    title Lundi Matin Test
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags

  body
    .header
      = link_to "Rechercher un contact", clients_path

    .container
      - if notice.present?
        .alert.alert-notice = notice
      - if alert.present?
        .alert.alert-alert = alert

      = yield